### ISSUE TITLE
create / update documentation

### ISSUE THREAD

**Issue by treee111** [treee111/wahooMapsCreator#80]
## Is your feature request related to a problem? Please describe.
New users need assistance.

## Describe the solution you'd like

- [x] Documentation for cruiser usage and map creation for cruiser
- [x] Creation of .json file for relevant tiles and use this file --> not needed anymore, X/Y CLI argument is possible - via #99
- [x] Clarify and unify Quickstart docu for macOS and Windows - via #84
- [x] documentation of cli arguments - via #170
- [x] document how to restore original maps
